### ISSUE TITLE
Restructure UX of search results and citations, optimizing for consistency

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-answer#48]
Sometimes a summary will cite some but not all search results. For example, it might cite search results 2, 3, and 5 but not 1 or 4. In these cases, listing those search results is a confusing UX.

We should address this by restructuring the UX to optimize for consistency between the citations and the results shown. For example, the end result could look like this:
1. Hide all results until the summary is returned
2. Reduce the search results to only those cited by the summary
3. Normalize the search results and the citations according to the reduced list. For example, if only 2, 3, and 5 are used, then re-label those as 1, 2, and 3 and update the summary citations to use the new labels.

CC @ofermend

**Comment by cjcenizal** [comment]
CC @amin2718

**Comment by amin2718** [comment]
If you go with [3], you can even take it a step further and normalize it so that the first citation is always [1], the second is [2], etc. Then it corresponds exactly with how citations are traditionally handled in books and reports, smoothing the user experience further.

Brainstorming below:

Above the fold, all cited results should be shown. Below the fold (a horizontal divider, for example), the remaining search results should be shown, perhaps with a label ("These might also be relevant").
